## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.3
  - nightly

notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  allow_failures:
  - julia: nightly

env:
  matrix:
    - JULIA_NUM_THREADS=1
    - JULIA_NUM_THREADS=4
    - JULIA_NUM_THREADS=8
## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("PStdLib"); Pkg.test("PStdLib"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'using ECS; using Pkg; cd(dirname(dirname(pathof(ECS)))); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using ECS; using Pkg; cd(dirname(dirname(pathof(ECS)))); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'using ECS; cd(dirname(dirname(pathof(ECS)))); include(joinpath("docs", "make.jl"))'

# jobs:
#   include:
#     - name: "Benchmark"
#       julia: 1.3
#       os: linux
#       before_script:
#         - git fetch origin '+refs/heads/master:refs/remotes/origin/master'
#         - git branch master origin/master
#         # Run benchmark outside `script` so that it's hidden by default:
#         - julia -e 'using Run; Run.script("benchmark/runjudge.jl")'
#       script:
#         - julia -e 'using Run; Run.script("benchmark/pprintjudge.jl")'
#       after_success: skip
#       if: NOT (branch = master)
