name = "ECS"
uuid = "1ada24be-c16d-4464-9f61-27c2e0f16645"
authors = ["louisponet <louisponet@gmail.com>"]
version = "0.1.0"

[deps]
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
